## Check for vulnerabilities
name: Security scanning
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups
    steps:
      - name: Checkout code
        uses: actions/checkout@v2